feat(Contract): Post Audit features request
WavesHQ/quantum pull request #580
Opened 2023-02-27 09:24 UTC by Abhishekkochar

#### What this PR does / why we need it:
Added cap on tx fee,
Should be able to flush fund per token and also by providing `from` and `to` index
#### Which issue(s) does this PR fixes?:

Fixes #579

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-02-27 10:30 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +            (bool sent, ) = _flushReceiveAddress.call{value: amount}('');
Oh, we can't just use `flushReceiveAddress` (the constant) here? 🤔

2023-02-27 10:59 UTC, weiyuan95 requested changes

2023-02-27 10:59 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +     * anyone can call this function, if pass (0,3), only token at index 0, 1 and 2 will be flushed.
```suggestion
     * anyone can call this function. For example, calling flushMultipleTokenFunds(0,3), only the tokens at index 0, 1 and 2 will be flushed.
```

Let's call the function `flushMultipleTokenFunds`

2023-02-27 10:59 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +     * @param _fromIndex Finishing index for array `supportedTokens.values()` to flush from
```suggestion
     * @param _fromIndex End index for array `supportedTokens.values()` to flush from
```

2023-02-27 10:59 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +        if (_toIndex > supportedTokens.length()) revert INVALID_TOINDEX();
Does solidity expect indexes less than 0? We should check `_fromIndex >= 0` as well? 🤔

2023-02-27 10:59 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.transactionFee.spec.ts
> +      // Admin should successfully changes the tx fees to 101%
```suggestion
      // Admin should not be able to change the tx fees to more than 100%
```

2023-02-27 10:59 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.flushFund.spec.ts
> +  it('Should flush the funds successfully when there is initial redundant funds per `tokenAddress`', async () => {
```suggestion
  it('Should flush the funds per token successfully when there is initial redundant funds per `tokenAddress`', async () => {
```

This is for the per token scenario?

2023-02-27 22:34 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +            (bool sent, ) = _flushReceiveAddress.call{value: amount}('');
It's not a constant though. It is a state variable.

2023-02-27 22:39 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.flushFund.spec.ts
> +  it('Should flush the funds successfully when there is initial redundant funds per `tokenAddress`', async () => {
Oh yes, fixed

2023-02-27 22:44 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +        if (_toIndex > supportedTokens.length()) revert INVALID_TOINDEX();
This is an `uint256 _fromIndex` We can't pass index that is less than 0 or negative here to start with.

2023-02-27 23:16 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +        if (_toIndex > supportedTokens.length()) revert INVALID_TOINDEX();
![Uploading Screenshot 2023-02-28 at 12.15.06 PM.png…]()

2023-02-28 00:03 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +        if (_toIndex > supportedTokens.length()) revert INVALID_TOINDEX();
<img width="1111" alt="Screenshot 2023-02-28 at 12 15 06 PM" src="https://user-images.githubusercontent.com/43106142/221717227-8ba8fc4b-a207-4fae-a9fe-e86e750b53c9.png">

2023-02-28 02:09 UTC, cuongquangnam requested changes

2023-02-28 02:13 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +        address _flushReceiveAddress = flushReceiveAddress;
Actually yes, you are right. Forgot to see that was conditional.

2023-02-28 02:22 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    function flushFundPerToken(address _tokenAddress) external {
Good point, However, I don't see the case where we will have the funds of unsupported token.

2023-02-28 02:24 UTC, cuongquangnam commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    function flushFundPerToken(address _tokenAddress) external {
I think better have a guard rather than not, because it is open to public, not like withdraw function where only privileged ones can access

2023-02-28 04:19 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +            (bool sent, ) = _flushReceiveAddress.call{value: amount}('');
Ah, set after init. Got it.

2023-02-28 04:21 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    function flushFundPerToken(address _tokenAddress) external {
Let's have this guard as a sanity check. For withdraw, yes, it's ok to not make the check, but when it comes to flushing the funds we should only need to flush for tokens we support 🤔

2023-02-28 04:25 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +        if (_toIndex > supportedTokens.length()) revert INVALID_TOINDEX();
Ah, got it. It's `uint` so it cannot be negative.

2023-02-28 04:28 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +     * @param _toIndex Starting index for array `supportedTokens.values()` to flush to
Good point on the `inclusive` and `exclusive`.

2023-02-28 08:30 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.flushFund.spec.ts
> +  it('Should revert if ERC20 no supported', async () => {
```suggestion
  it('Should revert if ERC20 is not supported', async () => {
```

2023-02-28 09:02 UTC, merged