Add timelock as per audit suggestions
WavesHQ/quantum pull request #587
Opened 2023-02-27 16:31 UTC by cuongquangnam

#### What this PR does / why we need it:
Add timelock contract
My current idea for how this should work:
- We deploy one TimelockController as a DEFAULT_ADMIN_ROLE who can withdraw money from the bridge contract.
- We deploy another TimelockController as a OPERATIONAL_ADMIN_ROLE who can change configuration parameters.

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-02-28 05:07 UTC, weiyuan95 commented
For posterity: 

We will be having 2 roles
- `DEFAULT_ADMIN` role, where the address is the TimeLock contract
- `withdraw` role, where the address is the multisig contract

They are mutually exclusive roles, where the withdraw role can _only_ call withdraw funds. Every other state-change method call must go through the TimeLock contract via the `DEFAULT_ADMIN` role.

The TimeLock contract will also have a proposer and executor role that is tied to the multisig contract as well. The minimum delay will be 3 days.

2023-03-01 03:16 UTC, weiyuan95 requested changes
LGTM, just some minor comments.

Issue to improve test coverage is tracked in #600

2023-03-01 03:16 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +  // not necessary tests
Agree that these are probably not necessary since we know how the initializer works now. Let's just delete instead of commenting it out.

2023-03-01 03:16 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
> +      // Test should be revert with a mention string if requesting amount bigger than actual balance of the Bridge.
```suggestion
      // Test should revert if requesting amount bigger than actual balance of the Bridge.
```

2023-03-01 03:16 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
> +      // sanity check on whether we need to make the defaultadminsigner.address to lower-case
Hmm, what's this? Don't see any lower case conversion going on here.

2023-03-01 04:50 UTC, Abhishekkochar requested changes
Quick fix, Everything else LGTM.

2023-03-01 04:50 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/test/reinitialize/BridgeV2TestNet.sol
> +    function version() external view returns (string memory) {
Please move this view fn() with other view fn(), at the end of contract. Same for BridgeV1. 
This is my bad, I placed  it right after init.

2023-03-01 06:13 UTC, cuongquangnam commented on packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
> +      // sanity check on whether we need to make the defaultadminsigner.address to lower-case
Oh, just a sanity check to see whether I need to transform the address to lower case when inputting into the hasRole function like the case of AccessControl error:
``` 
`AccessControl: account ${defaultAdminSigner.address.toLowerCase()} is missing role ${WITHDRAW_ROLE}`
```

2023-03-01 06:45 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
> +      // sanity check on whether we need to make the defaultadminsigner.address to lower-case
Ah - it's below. Got it.

2023-03-01 06:47 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
> +      // sanity check on whether we need to make the defaultadminsigner.address to lower-case
I can do it from a suggestion

2023-03-01 06:48 UTC, weiyuan95 requested changes

2023-03-01 06:48 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
> +      await expect(proxyBridge.connect(defaultAdminSigner).withdraw(testToken.address, toWei('20'))).to.be.revertedWith(
```suggestion
      expect(await proxyBridge.hasRole(`0x${'0'.repeat(64)}`, defaultAdminSigner.address)).to.equal(true);
      expect(await proxyBridge.hasRole(WITHDRAW_ROLE, defaultAdminSigner.address)).to.equal(false);
      // Withdrawal by defaultAdminSigner should be rejected if it has not been granted WITHDRAW_ROLE
      // sanity check on whether we need to make the defaultadminsigner.address to lower-case
      await expect(proxyBridge.connect(defaultAdminSigner).withdraw(testToken.address, toWei('20'))).to.be.revertedWith(
```

2023-03-01 06:48 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
> +      expect(await proxyBridge.hasRole(WITHDRAW_ROLE, arbitrarySigner.address)).to.equal(false);
```suggestion
      expect(await proxyBridge.hasRole(WITHDRAW_ROLE, arbitrarySigner.address)).to.equal(false);
      // sanity check on whether we need to make the defaultadminsigner.address to lower-case
```

2023-03-01 06:56 UTC, cuongquangnam commented on packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
> +      // sanity check on whether we need to make the defaultadminsigner.address to lower-case
do we need this comment here?

2023-03-01 06:58 UTC, cuongquangnam commented on packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
> +      // sanity check on whether we need to make the defaultadminsigner.address to lower-case
hmm, the comment is not about this error, haha. It is more about my surprise that solidity error transforms the address to lowercase when emitting an error. So I check again whether I need to transform address into lowercase  when passing them into functions

2023-03-01 08:45 UTC, weiyuan95 approved these changes

2023-03-01 08:46 UTC, merged