docs(ReadMe): Updated with correct addresses and user guide on new implementation
WavesHQ/quantum pull request #622
Opened 2023-03-02 04:33 UTC by Abhishekkochar

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-03-03 00:57 UTC, weiyuan95 commented on README.md
> +- The target address is the Proxy Bridge. The value will usually be 0. The data is the encoded data of the function and arguments (BridgeV1Interface.encodeFunctionData('changeTxFee', [100])). The pre
Let's mention that predecessor should almost always be 0x0 unless we have a prerequisite transaction, and that the delay represents the minimum amount of time before the tx can be executed.

Is the delay in seconds or ms?

2023-03-03 01:35 UTC, Abhishekkochar commented on README.md
> +- The target address is the Proxy Bridge. The value will usually be 0. The data is the encoded data of the function and arguments (BridgeV1Interface.encodeFunctionData('changeTxFee', [100])). The pre
Always in seconds. I will mentions this as well.

2023-03-03 06:38 UTC, cuongquangnam requested changes

2023-03-03 06:38 UTC, cuongquangnam commented on README.md
> +We are implementing a TimeLock contract that will work as an Admin address for ADMIN ONLY tx. There will be 3 days delay on every operational tx except when calling `Withdraw()` function.
Timelock cannot withdraw iirc?

2023-03-03 06:38 UTC, cuongquangnam commented on README.md
> +Gnosis safe will be implemented with both proposers and executors roles. Gnosis Safe has the authority to grant roles to addresses, as long as it holds the corresponding role itself. When revoking pr
What do you mean by the corresponding role itself?

2023-03-03 06:38 UTC, cuongquangnam commented on README.md
> +- After providing the contract address and ABI, the developer can select the contract method (in this case, we will try to change the transaction fee).
should we say clearly we should provide the TimelockController address and its abi here?

2023-03-03 06:38 UTC, cuongquangnam commented on README.md
> +The TimeLock contract is assigned the DEFAULT_ADMIN_ROLE, while another Gnosis Safe is assigned the WITHDRAW_ROLE. The DEFAULT_ADMIN_ROLE has the ability to change both roles to other addresses, but
```suggestion
The TimeLock contract is assigned the DEFAULT_ADMIN_ROLE, while another Gnosis Safe is assigned the WITHDRAW_ROLE. The DEFAULT_ADMIN_ROLE has the ability to grant both roles to other addresses, but this change will only take effect after three days.
```

2023-03-03 06:38 UTC, cuongquangnam commented on README.md
> +Only address with the Admin role can call the `addSupportedTokens()` function. This sets the `_tokenCap` for an ERC20 token and ETH identified by its `_tokenAddress`. All added tokens will be instant
```suggestion
Only address with the Admin role of the BridgeProxy contract can call the `addSupportedTokens()` function. This sets the `_tokenCap` for an ERC20 token and ETH identified by its `_tokenAddress`. All added tokens will be instantly supported by the bridge.
```

2023-03-03 06:38 UTC, cuongquangnam commented on README.md
> +Only address with the Admin role can call the `removeSupportedTokens()` function. This also sets the `_tokenCap` to `0`.
```suggestion
Only address with the Admin role of BridgeProxy contract can call the `removeSupportedTokens()` function. This also sets the `_tokenCap` to `0`.
```

2023-03-03 06:38 UTC, cuongquangnam commented on README.md
> +`withdraw()` function when called will withdraw an ERC20 token and ETH (address == 0x0). Only the address with the WITHDRAW role can call this function.
```suggestion
`withdraw()` function when called will withdraw an ERC20 token and ETH (address == 0x0). Only the address with the WITHDRAW role of BridgeProxy contract can call this function.
```

2023-03-03 06:38 UTC, cuongquangnam commented on README.md
>  `flushFund` function to flush the excess funds `(token.balanceOf(Bridge) - tokenCap)` across supported tokens to a hardcoded address (`flushReceiveAddress`) anyone can call this function. This applie
should change documentation about flushFund here?

2023-03-03 06:38 UTC, cuongquangnam commented on README.md
> +Admin address can change `flushReceiveAddress`.
Admin address of BridgeProxy contract

2023-03-03 06:38 UTC, cuongquangnam commented on README.md
> +Admin address can change `relayerAddress`.
Admin address of BridgeProxy contract

2023-03-03 06:38 UTC, cuongquangnam commented on README.md
> +Only address with Admin role can change `transactionFee`.
Admin role of bridgeproxy contract

2023-03-03 06:38 UTC, cuongquangnam commented on README.md
> +Only address with admin role can change `communityWallet`. This is where the tx fees upon bridging will go.
admin role of bridgeProxy contract

2023-03-03 06:38 UTC, cuongquangnam commented on README.md
> +Only address with admin role can change `tokenCap`.
admin role of bridgeproxy contract

2023-03-03 06:38 UTC, cuongquangnam commented on README.md
> +ETH and ERC20 tokens can be withdrawn by the address with WITHDRAW_ROLE only via the `withdraw(address _tokenAddress, uint256 amount)` function.
WITHDRAW_ROLE of bridgeproxy contract

2023-03-03 06:38 UTC, cuongquangnam commented on README.md
> +Admin address will be Gnosis safe, ideally will be with at least 3 owners with a 2/3 quorum.
Admin address of TimelockController contract

2023-03-03 06:38 UTC, cuongquangnam commented on README.md
> +Admin address will be Gnosis safe, ideally will be with at least 3 owners with a 2/3 quorum.
and how about withdraw_role of BridgeProxy? 
I think let this be discussed off-Github

2023-03-03 08:18 UTC, Abhishekkochar commented on README.md
> +We are implementing a TimeLock contract that will work as an Admin address for ADMIN ONLY tx. There will be 3 days delay on every operational tx except when calling `Withdraw()` function.
Yes, this is what it says as well.

2023-03-03 08:22 UTC, Abhishekkochar commented on README.md
> +- After providing the contract address and ABI, the developer can select the contract method (in this case, we will try to change the transaction fee).
Guide is pretty explanatory. They will have to look this as a guide anyway.

2023-03-03 08:26 UTC, Abhishekkochar commented on README.md
> +Only address with the Admin role can call the `addSupportedTokens()` function. This sets the `_tokenCap` for an ERC20 token and ETH identified by its `_tokenAddress`. All added tokens will be instant
I don't think we need to add of `of the BridgeProxy contract` as the function we are calling is of BridgeProxy contract.

2023-03-03 08:27 UTC, Abhishekkochar commented on README.md
> +ETH and ERC20 tokens can be withdrawn by the address with WITHDRAW_ROLE only via the `withdraw(address _tokenAddress, uint256 amount)` function.
`WITHDRAW_ROLE ` is only in BridgeProxy contract.

2023-03-03 08:30 UTC, cuongquangnam commented on README.md
> +We are implementing a TimeLock contract that will work as an Admin address for ADMIN ONLY tx. There will be 3 days delay on every operational tx except when calling `Withdraw()` function.
hmm, the way it writes here indicates that Timelock contract can withdraw?

2023-03-03 08:32 UTC, Abhishekkochar commented on README.md
> +Gnosis safe will be implemented with both proposers and executors roles. Gnosis Safe has the authority to grant roles to addresses, as long as it holds the corresponding role itself. When revoking pr
If multi-sig wallet wants to give other wallet a proposers role, they can only do so if the executing account hold that role as well.

2023-03-06 06:24 UTC, cuongquangnam requested changes

2023-03-06 06:24 UTC, cuongquangnam commented on README.md
> +Gnosis safe will be implemented with both proposers and executors roles. Gnosis Safe has the authority to grant roles to addresses, as long as it holds the corresponding role itself. When revoking pr
```suggestion
Gnosis safe will be implemented with both proposers and executors roles. Only the Timelock smart contract has the role (TIMELOCK_ADMIN_ROLE) to grant roles for now. If we want to grant new roles to new addresses, have to go through a round of scheduling and executing the grantRole functions through the Timelock contract. When revoking privileges, either the revokeRole() or renounceRole() functions must be used.
```

2023-03-06 06:24 UTC, cuongquangnam commented on README.md
> +### TimeLock Contract Account Permission
## Timelock Contract Operation

2023-03-06 06:24 UTC, cuongquangnam commented on README.md
> +## Operational Transactions
```suggestion
## Bridge Contract operation
```

2023-03-06 06:24 UTC, cuongquangnam commented on README.md
> +The TimeLock contract is assigned the DEFAULT_ADMIN_ROLE, while another Gnosis Safe is assigned the WITHDRAW_ROLE. The DEFAULT_ADMIN_ROLE has the ability to grant both roles to other addresses, but t
actually, from the perspective of the bridge contract, the change will happen instantly after default_admin_role call the grantRole function?

2023-03-06 06:24 UTC, cuongquangnam commented on README.md
> +ETH and ERC20 tokens can be withdrawn by the address with WITHDRAW_ROLE only via the `withdraw(address _tokenAddress, uint256 amount)` function.
should we remove this one, cos it is a duplicate of a part before

2023-03-07 05:52 UTC, cuongquangnam requested changes
Except for the changes I suggested, everything else LGTM

2023-03-07 05:52 UTC, cuongquangnam commented on README.md
> +### TimeLock Contract Operations
should be two hash symbol?

2023-03-07 05:52 UTC, cuongquangnam commented on README.md
> +The reason behind choosing different salt is to avoid having he same operation identifier again.
"the same operation identifier"

2023-03-07 05:52 UTC, cuongquangnam commented on README.md
> +The TimeLock contract is assigned the DEFAULT_ADMIN_ROLE, while another Gnosis Safe is assigned the WITHDRAW_ROLE. The DEFAULT_ADMIN_ROLE has the ability to grant both roles to other addresses, but t
"these changes will happen ..."

2023-03-07 06:28 UTC, cuongquangnam approved these changes

2023-03-07 08:00 UTC, weiyuan95 commented on README.md
> +####
```suggestion
## Contract Operations
```

2023-03-07 08:02 UTC, weiyuan95 approved these changes

2023-03-07 08:19 UTC, merged